// 실행: npx prisma db seed (또는 npx tsx prisma/seed.ts)
// 사단법인 깊은순종 실제 공개 게시물 제목/날짜(스크랩 확보)와, 이미 보유 중인
// 자체 활동 사진(my-website/images)을 이용해 초기 데이터를 채운다.
import "dotenv/config";
import { PrismaClient, BoardType } from "../app/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { parseShortDate } from "../lib/dates";
import { prepareSeedImages, albumImages } from "./prepare-images";

const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.post.deleteMany();

  await prisma.post.createMany({
    data: [
      // 사업소식 (실제 사이트 www.deepob.or.kr 사업소식 게시판 1~24번 전체를 그대로 이전)
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2026년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "1. 사업대상 : 시각장애부모의 비장애자녀 10명, 전문강사 10명, 시각장애부모 10명\n\n2. 대상자 선정 : 관악구 관내 실로암 시각장애인 복지관과 협력하여 지원학생 선정\n\n3. 사업내용 :  시각장애인 부모를 둔 비장애자녀에게 전문강사 멘토를 1:1로 매칭하여 시각장애인 부모가 지원하기 어려운 학습활동, 야외체험활동, 정서멘토링 등을 지원\n\n4. 기대효과 : 시각장애인 부모의 양육 부담을 경감하고, 시각장애인 부모 가정의 건강한 가족 기능 회복을 도모",
        authorName: "관리자",
        createdAt: parseShortDate("26.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2026년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어발달 및 학습지도)",
        content: "1. 사업대상 : 관악구 관내 저소득 취약계층 다문화가족 자녀 중 언어발달 및 학습 지연을 가진 아동 3명\n\n2. 대상자 선정 : 관악구 가족센터와 협의하여 선정\n\n3. 사업내용 :\n    ○ 주 1~2회 총 50회 활동가를 통한 언어발달지원 및 학습지원\n \n\n4. 기대효과 : 언어발달 및 학습 지연을 가진 다문화가족 아동에게 맞춤형 교육 서비스를 제공하여 아동의 건강한 성장을 지원함",
        authorName: "관리자",
        createdAt: parseShortDate("26.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2026년 저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        content: "1. 사업대상 : 관악구 관내 취약계층 아동 중 심리치료가 필요한 아동 8명\n\n2. 대상자 선정 : 관악구 노인청소년과 드림스타트팀과 협의하여 선정\n\n3. 사업내용 :\n    ○ 주 1회 심리치료비 지원\n    ○ 치료내용 : 놀이치료, 언어치료, 감각통합치료 등\n\n4. 기대효과 : 아동의 문제행동 및 심리·인지 등 발달지연의 원인을 조기에 발견하고 치료함으로써 정서적 안정과 건강한 성장·발달 도모",
        authorName: "관리자",
        createdAt: parseShortDate("26.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2026년 지역의 사회복지시설을 통한 저소득 취약계층 자립 지원(스마트 워커 육성을 위한 컴퓨터 코딩교육)",
        content: "1. 사업대상 : 쪽방촌 지역아동센터, 신림동 하늘지역아동센터 아동 중 기초코딩 교육이 필요한 초등학생 14명\n\n2. 대상자 선정 : 쪽방촌 소망을 찾는 이 지역아동센터, 신림동 하늘지역아동센터와 협력하여 선정\n\n3. 사업내용 :   \n    ○ 주1회 60분수업,  기초코딩교육 \n    ○ 교육내용 : 게임만들기로 배우는 스크래치, 마이크로비트로 배우는 스크래치, 로블록스 스튜디오\n                      \n4. 기대효과 : 4차산업시대에 맞는 정보, 기술 습득과 코딩교육을 통해 디지털화된 정보를 공유하고 활용할 수 있는 기술을 습득하며 이를 통해 문제해결 능력, 커뮤니케이션 능력 향상은 물론 프로그래밍 지식으로 세계를 더 잘 이해할 수 있는 인재양성",
        authorName: "관리자",
        createdAt: parseShortDate("26.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2026년 저소득 취약계층 무상급식 및 생활지원(밑반찬 지원사업)",
        content: "1. 사업대상 : 저소득 취약계층(독거노인, 장애인, 한부모가족 등) 주민 중 균형잡힌 식생활 유지가 어려우나 타기관으로 부터 지원을 받지 못하는 대상자 64명\n\n2. 대상자 선정 : 관악구 낙성대동, 행운동, 인헌동, 보라매동 주민센터 복지담당자 및 관악구 노인청소년과 드림스타트팀과 협의하여 선정\n\n3. 사업내용 : 대상자에게 주2회(월요일, 목요일) 자원봉사자와 협력하여 밑반찬 제공\n\n4. 기대효과 : 저소득 취약계층 대상자에게 밑반찬을 지원함으로써 결식을 예방하고 건강증진 도모",
        authorName: "관리자",
        createdAt: parseShortDate("26.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2025년 지역의 사회복지시설을 통한 저소득 취약계층 자립 지원(스마트 워커 육성을 위한 코딩교육) - 관악구 신림동 하늘지역아동센터",
        content: "1. 사업대상 : 관악구 신림동 하늘지역아동센터 아동 중 기초코딩 교육이 필요한 초등학생 및 중학생 8명\n\n2. 대상자 선정 : 하늘지역아동센터와 협력하여 선정\n\n3. 사업내용 :   \n    ○ 10회(1회 90분수업)  기초코딩교육(2025. 1. 6 ~ 2025. 1. 20) \n    ○ 교육내용 : 게임만들기로 배우는 스크래치\n \n4. 기대효과 : 4차산업시대에 맞는 정보, 기술 습득과 코딩교육을 통해 디지털화된 정보를 공유하고 활용할 수 있는 기술을 습득하며 이를 통해 문제해결 능력, 커뮤니케이션 능력 향상은 물론 프로그래밍 지식으로 세계를 더 잘 이해할 수 있는 인재양성",
        authorName: "관리자",
        createdAt: parseShortDate("25.01.20"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2025년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "1. 사업대상 : 시각장애부모의 비장애자녀 14명, 학습도우미 14명, 시각장애부모 14명\n\n2. 대상자 선정 : 관악구 관내 실로암 시각장애인 복지관과 협력하여 지원학생 및 자원봉사대학생 선정\n\n3. 사업내용 :  시각장애인 부모를 둔 비장애자녀에게 대학생 멘토를 1:1로 매칭하여 시각장애인 부모가 지원하기 어려운 학습활동, 야외체험활동, 정서멘토링 등을 지원\n\n4. 기대효과 : 시각장애인 부모의 양육 부담을 경감하고, 시각장애인 부모 가정의 건강한 가족 기능 회복을 도모",
        authorName: "관리자",
        createdAt: parseShortDate("25.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2025년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어발달 및 학습지도)",
        content: "1. 사업대상 : 관악구 관내 저소득 취약계층 다문화가족 자녀 중 언어발달 및 학습 지연을 가진 아동 3명\n\n2. 대상자 선정 : 관악구 가족센터와 협의하여 선정\n\n3. 사업내용 :\n    ○ 주 1~2회 총 50회 활동가를 통한 언어발달지원 및 학습지원\n \n\n4. 기대효과 : 언어발달 및 학습 지연을 가진 다문화가족 아동에게 맞춤형 교육 서비스를 제공하여 아동의 건강한 성장을 지원함",
        authorName: "관리자",
        createdAt: parseShortDate("25.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2025년 저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        content: "1. 사업대상 : 관악구 관내 취약계층 아동 중 심리치료가 필요한 아동 8명\n\n2. 대상자 선정 : 관악구 노인청소년과 드림스타트팀과 협의하여 선정\n\n3. 사업내용 :\n    ○ 주 1회 심리치료비 지원\n    ○ 치료내용 : 놀이치료, 언어치료, 감각통합치료 등\n\n4. 기대효과 : 아동의 문제행동 및 심리·인지 등 발달지연의 원인을 조기에 발견하고 치료함으로써 정서적 안정과 건강한 성장·발달 도모",
        authorName: "관리자",
        createdAt: parseShortDate("25.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2025년 지역의 사회복지시설을 통한 저소득 취약계층 자립 지원(스마트 워커 육성을 위한 코딩교육) - 쪽방촌 소망을 찾는 이 지역아동센터",
        content: "1. 사업대상 : 쪽방촌 지역아동센터 아동 중 기초코딩 교육이 필요한 초등학생 6명\n\n2. 대상자 선정 : 쪽방촌 소망을 찾는 이 지역아동센터와 협력하여 선정\n\n3. 사업내용 :   \n    ○ 주1회 60분수업,  기초코딩교육 \n    ○ 교육내용 : 게임만들기로 배우는 스크래치, 마이크로비트로 배우는 스크래치\n                      \n4. 기대효과 : 4차산업시대에 맞는 정보, 기술 습득과 코딩교육을 통해 디지털화된 정보를 공유하고 활용할 수 있는 기술을 습득하며 이를 통해 문제해결 능력, 커뮤니케이션 능력 향상은 물론 프로그래밍 지식으로 세계를 더 잘 이해할 수 있는 인재양성",
        authorName: "관리자",
        createdAt: parseShortDate("25.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "2025년 저소득 취약계층 무상급식 및 생활지원(밑반찬 지원사업)",
        content: "1. 사업대상 : 저소득 취약계층(독거노인, 장애인, 한부모가족 등) 주민 중 균형잡힌 식생활 유지가 어려우나 타기관으로 부터 지원을 받지 못하는 대상자 64명\n\n2. 대상자 선정 : 관악구 낙성대동, 행운동, 인헌동, 보라매동(2025년 추가) 주민센터 복지담당자 및 관악구 노인청소년과 드림스타트팀과 협의하여 선정\n\n3. 사업내용 : 대상자에게 주2회(월요일, 목요일) 자원봉사자와 협력하여 밑반찬 제공\n\n4. 기대효과 : 저소득 취약계층 대상자에게 밑반찬을 지원함으로써 결식을 예방하고 건강증진 도모",
        authorName: "관리자",
        createdAt: parseShortDate("25.01.02"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "밑반찬 추가 지원",
        content: "1. 8월부터 저소득 취약계층 주민 중 식생활 유지가 어려우나 타기관으로 부터 지원을 받지 못하는 대상자 2명 추가 총 59명 밑반찬 지원(2024년 대상자 57명)",
        authorName: "관리자",
        createdAt: parseShortDate("24.08.01"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "지역의 사회복지시설을 통한 저소득 취약계층 자립 지원(스마트 워커 육성을 위한 코딩교육) - 관악구 인헌동 한우리지역아동센터",
        content: "1. 사업대상 : 관악구 인헌동 한우리지역아동센터 아동 중 기초코딩 교육이 필요한 초등학생 및 중학생 10명\n\n2. 대상자 선정 : 한우리지역아동센터와 협력하여 선정\n\n3. 사업내용 :   \n    ○ 10회(1회 90분수업)  기초코딩교육(2024. 7. 29 ~ 2024. 8. 13) \n    ○ 교육내용 : 게임만들기로 배우는 스크래치\n \n4. 기대효과 : 4차산업시대에 맞는 정보, 기술 습득과 코딩교육을 통해 디지털화된 정보를 공유하고 활용할 수 있는 기술을 습득하며 이를 통해 문제해결 능력, 커뮤니케이션 능력 향상은 물론 프로그래밍 지식으로 세계를 더 잘 이해할 수 있는 인재양성",
        authorName: "관리자",
        createdAt: parseShortDate("24.07.30"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "아동심리치료, 밑반찬 추가 지원",
        content: "1. 6월부터 관악구 관내 취약계층 아동 중 심리치료가 필요한 아동 4명 추가 총 8명 심리치료 지원\n\n2. 6월부터 저소득 취약계층 주민 중 식생활 유지가 어려우나 타기관으로 부터 지원을 받지 못하는 대상자 15명 추가 총 55명 밑반찬 지원",
        authorName: "관리자",
        createdAt: parseShortDate("23.06.01"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "저소득 취약계층 무상급식 및 생활 지원(다문화가족 긴급생활비 지원)",
        content: "1. 사업대상 : 관악구 관내 중위소득 100%이하 다문화가족\n\n2. 대상자 선정 : 관악구 가족센터에서 대상자를 추천하면 법인에서 심의 후 선정\n\n3. 사업내용 :\n    ○ 주거비 및 생계비 최대 30만원 지원(2023. 1. ~ 2023. 12.) \n\n4. 기대효과 : 실직 및 질병 등의 이유로 긴급하게 생계에 어려움을 겪는 다문화 가족에게 주거비 및 생계비를 지원하여 위기극복 및 자립에 기여",
        authorName: "관리자",
        createdAt: parseShortDate("23.01.11"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어발달 및 학습지도)",
        content: "1. 사업대상 : 관악구 관내 저소득 취약계층 다문화가족 자녀 중 언어발달 및 학습 지연을 가진 아동\n\n2. 대상자 선정 : 관악구 가족센터와 협의하여 선정\n\n3. 사업내용 :\n    ○ 주 1회 총 30회 활동가를 통한 언어발달지원 및 학습지원(2023. 1. ~ 2023. 12.) \n\n4. 기대효과 : 언어발달 및 학습 지연을 가진 다문화가족 아동에게 맞춤형 교육 서비스를 제공하여 아동의 건강한 성장을 지원함",
        authorName: "관리자",
        createdAt: parseShortDate("23.01.11"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "저소득 취약계층 의료비 지원(다문화가족 긴급 의료비 지원)",
        content: "1. 사업대상 : 관악구 관내 중위소득 100%이하 질병 및 장애 등으로 긴급하게 의료비가 필요한 다문화가족\n\n2. 대상자 선정 : 관악구 가족센터에서 대상자를 추천하면 법인에서 심의 후 선정\n\n3. 사업내용 :\n    ○ 일반치료비 최대 100만원 지원(2023. 1. ~ 2023. 12.) \n\n4. 기대효과 : 갑작스러운 위기상황으로 경제적, 심리적, 사회적 어려움에 처한 가정의 상황에 따른 긴급, 위기 자립에 기여",
        authorName: "관리자",
        createdAt: parseShortDate("23.01.11"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "지역의 사회복지시설을 통한 저소득 취약계층 자립 지원(스마트 워커 육성을 위한 코딩교육) - 쪽방촌 소망을 찾는 이 지역아동센터",
        content: "1. 사업대상 : 쪽방촌 지역아동센터 아동 중 기초코딩 교육이 필요한 초등학생 및 중학생 6명\n\n2. 대상자 선정 : 쪽방촌 소망을 찾는 이 지역아동센터와 협력하여 선정\n\n3. 사업내용 :   \n    ○ 주1회 60분수업,  기초코딩교육(2022. 12.~ ) \n    ○ 교육내용 : 게임만들기로 배우는 스크래치, 마이크로비트로 배우는 스크래치\n                      \n4. 기대효과 : 4차산업시대에 맞는 정보, 기술 습득과 코딩교육을 통해 디지털화된 정보를 공유하고 활용할 수 있는 기술을 습득하며 이를 통해 문제해결 능력, 커뮤니케이션 능력 향상은 물론 프로그래밍 지식으로 세계를 더 잘 이해할 수 있는 인재양성",
        authorName: "관리자",
        createdAt: parseShortDate("23.01.11"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "지역의 사회복지시설을 통한 저소득 취약계층 자립 지원(스마트 워커 육성을 위한 초등학생 코딩교육) - 상록보육원",
        content: "1. 사업대상 : 보육원 아동 중 기초코딩 교육이 필요한 초등학생 8명\n\n2. 대상자 선정 : 관악구 관내 상록보육원과 협력하여 선정\n\n3. 사업내용 :   \n    ○ 10회(1회 90분 수업)  기초코딩교육(2022. 7. 25 ~ 2022. 8. 5) \n    ○ 교육내용 : 게임만들기로 배우는 스크래치, 마이크로비트로 배우는 스크래치\n                      \n4. 기대효과 : 4차산업시대에 맞는 정보, 기술 습득과 코딩교육을 통해 디지털화된 정보를 공유하고 활용할 수 있는 기술을 습득하며 이를 통해 문제해결 능력, 커뮤니케이션 능력 향상은 물론 프로그래밍 지식으로 세계를 더 잘 이해할 수 있는 인재양성",
        authorName: "관리자",
        createdAt: parseShortDate("22.07.08"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "저소득 취약계층 자녀 교육 지원",
        content: "1. 사업대상 : 시각장애부모의 비장애자녀 13명, 학습도우미 13명, 시각장애부모 13명\n\n2. 대상자 선정 : 관악구 관내 실로암 시각장애인 복지관과 협력하여 지원학생 및 자원봉사대학생 선정\n\n3. 사업내용 :  시각장애인 부모를 둔 비장애자녀에게 대학생 멘토를 1:1로 매칭하여 시각장애인 부모가 지원하기 어려운 학습활동, 야외체험활동, 정서멘토링 등을 지원\n\n4. 기대효과 : 시각장애인 부모의 양육 부담을 경감하고, 시각장애인 부모 가정의 건강한 가족 기능 회복을 도모",
        authorName: "관리자",
        createdAt: parseShortDate("22.06.24"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        content: "1. 사업대상 : 관악구 관내 취약계층 아동 중 심리치료가 필요한 아동 4명\n\n2. 대상자 선정 : 관악구 노인청소년과 드림스타트팀과 협의하여 선정\n\n3. 사업내용 :\n    ○ 주 1회 심리치료비 지원(2022. 5. ~ 2022. 12.) \n    ○ 치료내용 : 놀이치료, 언어치료, 감각통합치료 등\n\n4. 기대효과 : 아동의 문제행동 및 심리·인지 등 발달지연의 원인을 조기에 발견하고 치료함으로써 정서적 안정과 건강한 성장·발달 도모",
        authorName: "관리자",
        createdAt: parseShortDate("22.06.23"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "저소득 취약계층 무상급식 및 생활지원(밑반찬 지원사업)",
        content: "1. 사업대상 : 저소득 취약계층(독거노인, 장애인, 한부모가족 등) 주민 중 균형잡힌 식생활 유지가 어려우나 타기관으로 부터 지원을 받지 못하는 대상자 29명\n\n2. 대상자 선정 : 관악구 낙성대동, 행운동, 인헌동 주민센터 복지담당자 및 관악구 노인청소년과 드림스타트팀과 협의하여 선정\n\n3. 사업내용 : 대상자에게 주2회(월요일, 목요일) 자원봉사자와 협력하여 밑반찬 제공\n\n4. 기대효과 : 저소득 취약계층 대상자에게 밑반찬을 지원함으로써 결식을 예방하고 건강증진 도모",
        authorName: "관리자",
        createdAt: parseShortDate("22.04.11"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "저소득 취약계층 자립지원(동명아동복지센터)",
        content: "저소득 취약계층 자립지원(동명아동복지센터)",
        authorName: "관리자",
        createdAt: parseShortDate("22.04.04"),
      },
      {
        board: BoardType.BUSINESS_NEWS,
        title: "저소득 취약계층 자립지원(상록보육원)",
        content: "저소득 취약계층 자립지원(상록보육원)",
        authorName: "관리자",
        createdAt: parseShortDate("22.04.04"),
      },

      // 공지사항 (실제 사이트 www.deepob.or.kr 공지사항 게시판 전체를 그대로 이전)
      {
        board: BoardType.NOTICE,
        title: "2025년 결산보고서류공시",
        content: "2025년 사단법인 깊은순종 결산보고서류를 첨부와 같이 공시합니다.\n\n[첨부]\n\n2025년 수입지출결산\n\n연간기부금모금액 및 활용실적 명세서\n\n재무상태표\n\n출연재산 등에 대한 보고서",
        authorName: "관리자",
        createdAt: parseShortDate("26.03.12"),
      },
      {
        board: BoardType.NOTICE,
        title: "2026년 정기 회원총회 개최",
        content: "수신:(사)깊은순종 회원\n제목: 2026년 정기 회원총회 개최\n1. 일시 : 2026년 2월 22일(일) 15:20\n2. 대상 : 법인 회원 58명\n3. 상정 안건 :\n   [안건1] 2025년 사업실적 및 결산(안)\n   [안건2] 2026년 사업계획 및 예산(안)\n4. 위임장 제출 안내\n   1) 대상 : 총회 당일 불가피한 사유로 총회에 참석할 수 없는 회원\n   2) 조치 : 위임장 양식을 작성하여 이메일(deepob@naver.com), 문자, 카톡, 종합봉사실 제출",
        authorName: "관리자",
        createdAt: parseShortDate("26.02.06"),
      },
      {
        board: BoardType.NOTICE,
        title: "2026-1차 이사회 개최",
        content: "수신:(사)깊은순종 임원\n제목: 2026-1차 이사회 개최\n1. 일시 : 2026년 1월 25일(일) 오후 3시 20분\n2. 대상 : 법인 임원\n3. 회의 안건 :\n   [안건1] 2025년 사업실적 및 결산(안) 총회 부의(안)\n   [안건2] 2026년 사업계획 및 예산(안) 총회 부의(안)\n   [안건3] 신입회원 승인(안)",
        authorName: "관리자",
        createdAt: parseShortDate("26.01.15"),
      },
      {
        board: BoardType.NOTICE,
        title: "2024년 결산보고서류공시",
        content: "2024년 사단법인 깊은순종 결산보고서류를 첨부와 같이 공시합니다.\n\n[첨부]\n\n2024년 수입지출결산\n\n연간기부금모금액 및 활용실적 명세서\n\n재무상태표\n\n출연재산 등에 대한 보고서",
        authorName: "관리자",
        createdAt: parseShortDate("25.03.25"),
      },
      {
        board: BoardType.NOTICE,
        title: "2025년 정기 회원총회 개최",
        content: "수신:(사)깊은순종 회원\n제목: 2025년 정기 회원총회 개최\n1. 일시 : 2025년 2월 16일(일) 15:10\n2. 대상 : 법인 회원 61명\n3. 상정 안건 :\n   [안건1] 2024년 사업실적 및 결산(안)\n   [안건2] 2025년 사업계획 및 예산(안)\n   [안건3] 임원 선임(안)\n   [안건4] 이사장 선임(안)\n4. 위임장 제출 안내\n   1) 대상 : 총회 당일 불가피한 사유로 총회에 참석할 수 없는 회원\n   2) 조치 : 보내드린 양식을 작성하여 이메일(deepob@naver.com), 문자, 카톡으로 제출",
        authorName: "관리자",
        createdAt: parseShortDate("25.02.03"),
      },
      {
        board: BoardType.NOTICE,
        title: "2025-1차 이사회 개최",
        content: "수신:(사)깊은순종 임원\n제목: 2025-1차 이사회 개최\n1. 일시 : 2025년 1월 26일(일) 오후 3시 10분\n2. 대상 : 법인 임원\n3. 회의 안건 :\n   [안건1] 2024년 사업실적 및 결산(안) 총회 부의(안)\n   [안건2] 2025년 사업계획 및 예산(안) 총회 부의(안)\n   [안건3] 임원 선임(안) 총회 부의(안)",
        authorName: "관리자",
        createdAt: parseShortDate("25.01.15"),
      },
      {
        board: BoardType.NOTICE,
        title: "2023년 결산보고서류공시",
        content: "2023년 사단법인 깊은순종 결산보고서류를 첨부와 같이 공시합니다.\n\n[첨부]\n\n2023년 수입지출결산\n\n연간기부금모금액 및 활용실적 명세서\n\n재무상태표\n\n출연재산 등에 대한 보고서",
        authorName: "관리자",
        createdAt: parseShortDate("24.03.18"),
      },
      {
        board: BoardType.NOTICE,
        title: "2024년 정기 회원총회 개최",
        content: "수신:(사)깊은순종 회원\n제목: 2024년 제1차 회원총회 개최\n1. 일시 : 2024년 2월 25일(일) 15:10\n2. 대상 : 법인 회원 62명\n3. 상정 안건 :\n   [안건1] 2023년 사업실적 및 결산(안)\n   [안건2] 2024년 사업계획 및 예산(안)\n   [안건3] 정관 개정(안)\n4. 위임장 제출 안내\n   1) 대상 : 총회 당일 불가피한 사유로 총회에 참석할 수 없는 회원\n   2) 조치 : 보내드린 양식을 작성하여 이메일(deepob@naver.com), 문자, 카톡으로 제출",
        authorName: "관리자",
        createdAt: parseShortDate("24.02.06"),
      },
      {
        board: BoardType.NOTICE,
        title: "2024-1차 이사회 개최",
        content: "수신:(사)깊은순종 임원\n제목: 2024-1차 이사회 개최\n1. 일시 : 2024년 1월 28일(일) 오후 3시 10분\n2. 대상 : 법인 임원(이사, 감사)\n3. 회의 안건 :\n   [안건1] 2023년 사업실적 및 결산(안) 총회 부의(안)\n   [안건2] 2024년 사업계획 및 예산(안) 총회 부의(안)\n   [안건3] 정관 개정(안) 총회 부의(안)\n   [안건4] 신입회원 승인(안)",
        authorName: "관리자",
        createdAt: parseShortDate("24.01.18"),
      },
      {
        board: BoardType.NOTICE,
        title: "2023 관악구 자원봉사 기본교육 및 활성화 캠페인",
        content: "일시: 2023.09.04(월), 오후 2시(1시 55분까지 입장 후 출석체크)\n\n내용: 1. 구글미트를 미리 다운받아 소통이 원할한 장소에서 참여해주세요.\n             (예: 독서실 ×,이동중 ×)\n         2. 교육 중 자리이탈 및 화면 전환하는 경우, 실적인정이 불가능 합니다.",
        authorName: "관리자",
        createdAt: parseShortDate("23.09.01"),
      },
      {
        board: BoardType.NOTICE,
        title: "2022년 결산보고서류공시",
        content: "2022년 사단법인 깊은순종 결산보고서류를 첨부와 같이 공시합니다.\n\n[첨부]\n\n2022년 수입지출결산\n\n연간기부금모금액 및 활용실적 명세서\n\n재무상태표\n\n출연재산 등에 대한 보고서",
        authorName: "관리자",
        createdAt: parseShortDate("23.03.08"),
      },
      {
        board: BoardType.NOTICE,
        title: "2023년 정기총회 개최",
        content: "수신:(사)깊은순종 회원\n제목: 2023년 제1차 회원총회 개최\n1. 일시 : 2023년 2월 26일(일) 20:00\n2. 대상 : 법인 회원 63명\n3. 상정 안건 :\n   [안건1] 2022년 사업실적 및 결산(안)\n   [안건2] 2023년 사업계획 및 예산(안)\n   [안건3] 정관 개정(안)\n   [안건4] 임원 해임 및 선임(안)\n4. 위임장 제출 안내\n   1) 대상 : 총회 당일 불가피한 사유로 총회에 참석할 수 없는 회원\n   2) 조치 : 2023년 2월 26일(일) 08:00~19:00 큰은혜교회 종합봉사실에 위임장 양식 비치 및 접수",
        authorName: "관리자",
        createdAt: parseShortDate("23.02.23"),
      },
      {
        board: BoardType.NOTICE,
        title: "2023-1차 이사회 개최",
        content: "수신:(사)깊은순종 이사\n제목: 2023-1차 이사회 개최\n1. 일시 : 2023년 1월 29일(일) 오후3시\n2. 대상 : 법인 이사 11명\n3. 회의 안건 :\n   [안건1] 2022년 사업실적 및 결산(안) 총회 부의(안)\n   [안건2] 2023년 사업계획 및 예산(안) 총회 부의(안)\n   [안건3] 정관 개정(안) 총회 부의(안)\n   [안건4] 임원 해임 및 선임(안) 총회 부의(안)",
        authorName: "관리자",
        createdAt: parseShortDate("23.01.12"),
      },
      {
        board: BoardType.NOTICE,
        title: "사단법인 깊은순종 홈페이지에 오신 것을 환영합니다.",
        content: "홈페이지가 새롭게 오픈하였으니 많은 관심과 사랑 부탁드립니다...",
        authorName: "관리자",
        createdAt: parseShortDate("22.03.28"),
      },

      // 활동소식 (실제 사이트 www.deepob.or.kr 활동소식 게시판 전체를 그대로 이전)
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2026년 저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        content: "2026년 저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        authorName: "관리자",
        createdAt: parseShortDate("26.07.01"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2026년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        content: "2026년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        authorName: "관리자",
        createdAt: parseShortDate("26.06.30"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2026년 상반기 관악구 신림동 하늘지역아동센터 코딩교육",
        content: "2026년 상반기 관악구 신림동 하늘지역아동센터 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("26.06.24"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2026년 상반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        content: "2026년 상반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("26.06.24"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2026년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "2026년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        authorName: "관리자",
        createdAt: parseShortDate("26.06.22"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "사단법인 깊은순종 2026년 제1차 회원총회",
        content: "사단법인 깊은순종 2026년 제1차 회원총회",
        authorName: "관리자",
        createdAt: parseShortDate("26.02.22"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "보건복지부장관 감사패 수상",
        content: "보건복지부장관 감사패 수상",
        authorName: "관리자",
        createdAt: parseShortDate("25.11.20"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2025년 추수감사절 과일 나눔",
        content: "큰은혜교회 영·유아부, 유치원부, 소년부, 초등부 아동들이 반찬나눔 대상자분들을 위해 과일을 보내왔습니다.\n아이들의 마음과 부모님, 교사, 목사님, 전도사님들께 감사드리며 61가정에 전달하였습니다.",
        authorName: "관리자",
        createdAt: parseShortDate("25.10.27"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2025년 추석 밑반찬 지원",
        content: "2025년 추석 밑반찬 지원",
        authorName: "관리자",
        createdAt: parseShortDate("25.10.02"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2025년 저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        content: "2025년 저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        authorName: "관리자",
        createdAt: parseShortDate("25.07.28"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2025년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        content: "2025년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        authorName: "관리자",
        createdAt: parseShortDate("25.07.25"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2025년 상반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        content: "2025년 상반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("25.07.23"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2025년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "2025년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        authorName: "관리자",
        createdAt: parseShortDate("25.07.17"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "사단법인 깊은순종 2025년 제1차 회원총회",
        content: "사단법인 깊은순종 2025년 제1차 회원총회",
        authorName: "관리자",
        createdAt: parseShortDate("25.02.16"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2025년 관악구 신림동 하늘지역아동센터 코딩교육",
        content: "2025년 관악구 신림동 하늘지역아동센터 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("25.01.20"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2024년 추석 밑반찬 지원",
        content: "2024년 추석 밑반찬 지원",
        authorName: "관리자",
        createdAt: parseShortDate("24.09.20"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2024년 관악구 인헌동 한우리지역아동센터 코딩교육",
        content: "2024년 관악구 인헌동 한우리지역아동센터 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("24.08.15"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2024년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "2024년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        authorName: "관리자",
        createdAt: parseShortDate("24.08.12"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2024년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        content: "2024년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        authorName: "관리자",
        createdAt: parseShortDate("24.08.07"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2024년 상반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        content: "2024년 상반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("24.04.23"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "사단법인 깊은순종 2024년 제1차 회원총회",
        content: "사단법인 깊은순종 2024년 제1차 회원총회",
        authorName: "관리자",
        createdAt: parseShortDate("24.02.25"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "관악구 저소득 취약계층 어르신 이불나눔",
        content: "관악구청 복지정책과 희망복지팀 요청으로 취약계층 치매어르신께 이불을 지원해 드렸습니다.",
        authorName: "관리자",
        createdAt: parseShortDate("24.01.19"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2023년 하반기 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "2023년 하반기 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        authorName: "관리자",
        createdAt: parseShortDate("24.01.03"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2023년 하반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        content: "2023년 하반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("23.12.26"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2023년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        content: "2023년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        authorName: "관리자",
        createdAt: parseShortDate("23.08.08"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2023년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "2023년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        authorName: "관리자",
        createdAt: parseShortDate("23.08.03"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2023년 상록보육원 코딩교육",
        content: "2023년 상록보육원 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("23.08.01"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        content: "쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        authorName: "관리자",
        createdAt: parseShortDate("23.07.24"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "낙성대동주민센터 동장 방문",
        content: "낙성대동주민센터 동장 방문",
        authorName: "관리자",
        createdAt: parseShortDate("23.04.19"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "아동 심리 상담 치료",
        content: "통합사례관리사인터뷰.mp4\n\n관악구청 복지가족국 노인청소년과 드림스타트팀 통합사례관리사 인터뷰",
        authorName: "관리자",
        createdAt: parseShortDate("23.03.27"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "2023년 아동 심리 상담 치료 지원",
        content: "2023년 아동 심리 상담 치료 지원",
        authorName: "관리자",
        createdAt: parseShortDate("23.03.20"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "저소득 취약계층 자녀 교육 지원(행복한 크리스마스)",
        content: "저소득 취약계층 자녀 교육 지원(행복한 크리스마스)",
        authorName: "관리자",
        createdAt: parseShortDate("22.12.27"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "밑반찬 지원",
        content: "밑반찬 지원",
        authorName: "관리자",
        createdAt: parseShortDate("22.08.25"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "저소득 취약계층 자녀 교육 지원(가족캠프)",
        content: "저소득 취약계층 자녀 교육 지원(가족캠프)",
        authorName: "관리자",
        createdAt: parseShortDate("22.08.16"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "사단법인 깊은순종 창립총회",
        content: "사단법인 깊은순종 창립총회",
        authorName: "관리자",
        createdAt: parseShortDate("22.04.01"),
      },
      {
        board: BoardType.ACTIVITY_NEWS,
        title: "사단법인 깊은순종 활동소식을 자세히 알려드립니다...",
        content: "사단법인 깊은순종 활동소식을 자세히 알려드립니다...",
        authorName: "관리자",
        createdAt: parseShortDate("22.03.28"),
      },
    ],
  });

  // 앨범게시판 (실제 사이트 www.deepob.or.kr 앨범게시판 전체를 그대로 이전)
  await prepareSeedImages();

  await prisma.post.createMany({
    data: [
      {
        board: BoardType.ALBUM,
        title: "2025년 저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        content: "2025년 저소득 취약계층 의료비 지원(취약계층 아동 심리 치료 지원)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/4612bf99-b7d8-47f4-b07e-e8140e8f194e.jpg",
        createdAt: parseShortDate("25.07.28"),
      },
      {
        board: BoardType.ALBUM,
        title: "2025년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        content: "2025년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/d7f4c0bc-9017-41f4-84ce-bfc79c898786.png",
        createdAt: parseShortDate("25.07.25"),
      },
      {
        board: BoardType.ALBUM,
        title: "2025년 상반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        content: "2025년 상반기 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        authorName: "관리자",
        thumbnailUrl: "/uploads/50472c6a-7557-425b-a8f7-5059e1333801.jpg",
        createdAt: parseShortDate("25.07.23"),
      },
      {
        board: BoardType.ALBUM,
        title: "2025년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "2025년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/a002c6b7-7841-4d5f-97eb-f93fe27f73b7.jpg",
        createdAt: parseShortDate("25.07.17"),
      },
      {
        board: BoardType.ALBUM,
        title: "2025년 하늘지역아동센터 코딩교육",
        content: "2025년 하늘지역아동센터 코딩교육",
        authorName: "관리자",
        thumbnailUrl: "/uploads/0e812912-17e1-4462-b9a2-d963f88d34fd.jpg",
        createdAt: parseShortDate("25.01.20"),
      },
      {
        board: BoardType.ALBUM,
        title: "2024년 저소득 취약계층 의료비 지원(아동심리치료비 지원)",
        content: "2024년 저소득 취약계층 의료비 지원(아동심리치료비 지원)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/4a74c597-2e12-4b3e-88f6-7a23403bbbc9.jpg",
        createdAt: parseShortDate("24.12.27"),
      },
      {
        board: BoardType.ALBUM,
        title: "2024년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        content: "2024년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/2f412df9-35ba-4d6e-8165-9afff85ad08d.jpg",
        createdAt: parseShortDate("24.09.06"),
      },
      {
        board: BoardType.ALBUM,
        title: "2024년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "2024년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/6119f4c4-9115-4636-82cd-b964b791ccc5.jpg",
        createdAt: parseShortDate("24.08.27"),
      },
      {
        board: BoardType.ALBUM,
        title: "2024년 한우리지역아동센터 코딩교육",
        content: "2024년 한우리지역아동센터 코딩교육",
        authorName: "관리자",
        thumbnailUrl: "/uploads/e01e5042-7f5e-4b26-86ef-593edb21c474.jpg",
        createdAt: parseShortDate("24.08.14"),
      },
      {
        board: BoardType.ALBUM,
        title: "2024년 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        content: "2024년 쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        authorName: "관리자",
        thumbnailUrl: "/uploads/9b1c1461-d461-47e4-914a-e517789e25a2.jpg",
        createdAt: parseShortDate("24.05.20"),
      },
      {
        board: BoardType.ALBUM,
        title: "2023년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        content: "2023년 저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어학습지원)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/b1894d9e-ebc5-4f9a-a00a-4276a9bea6b3.png",
        createdAt: parseShortDate("23.08.08"),
      },
      {
        board: BoardType.ALBUM,
        title: "2023년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        content: "2023년 저소득 취약계층 자녀 교육 지원(시각장애인부모의 자녀 교육 지원)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/a558482e-ca31-4733-838a-1b710e132117.jpg",
        createdAt: parseShortDate("23.08.04"),
      },
      {
        board: BoardType.ALBUM,
        title: "2023년 상록보육원 코딩교육",
        content: "2023년 상록보육원 코딩교육",
        authorName: "관리자",
        thumbnailUrl: "/uploads/49f89f48-9980-4bc8-82b4-8929fd064ff8.jpg",
        createdAt: parseShortDate("23.08.04"),
      },
      {
        board: BoardType.ALBUM,
        title: "쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        content: "쪽방촌 소망을 찾는 이 지역아동센터 코딩교육",
        authorName: "관리자",
        thumbnailUrl: "/uploads/986922bf-fda6-4249-b171-35467f16356e.jpg",
        createdAt: parseShortDate("23.07.26"),
      },
      {
        board: BoardType.ALBUM,
        title: "낙성대동주민센터 동장 방문",
        content: "낙성대동주민센터 동장 방문",
        authorName: "관리자",
        thumbnailUrl: "/uploads/2678ba46-a4c6-4ae1-9043-c74fa17ebb0e.jpg",
        createdAt: parseShortDate("23.04.19"),
      },
      {
        board: BoardType.ALBUM,
        title: "관악구청 노인청소년과 드림스타트팀 관계자 방문",
        content: "관악구청 노인청소년과 드림스타트팀 관계자 방문",
        authorName: "관리자",
        thumbnailUrl: "/uploads/54b53b79-89c9-46ed-9212-a60f16406f42.jpg",
        createdAt: parseShortDate("23.03.20"),
      },
      {
        board: BoardType.ALBUM,
        title: "쪽방촌 지역아동센터 코딩교육(소망을 찾는 이 지역아동센터)",
        content: "쪽방촌 지역아동센터 코딩교육(소망을 찾는 이 지역아동센터)",
        authorName: "관리자",
        thumbnailUrl: "/uploads/7a1ab91e-6f09-4670-8655-e42e50eef2bc.jpg",
        createdAt: parseShortDate("23.01.11"),
      },
      {
        board: BoardType.ALBUM,
        title: "시각장애인가정 행복한 크리스마스",
        content: "시각장애인가정 행복한 크리스마스",
        authorName: "관리자",
        thumbnailUrl: "/uploads/a990c2d0-be19-4443-bddf-2e1d3ed4c2b3.jpg",
        createdAt: parseShortDate("22.12.27"),
      },
      {
        board: BoardType.ALBUM,
        title: "쌀나눔",
        content: "쌀나눔",
        authorName: "관리자",
        thumbnailUrl: "/uploads/0f80c455-cce7-4de9-a2b5-d972382d5b47.jpg",
        createdAt: parseShortDate("22.11.13"),
      },
      {
        board: BoardType.ALBUM,
        title: "밑반찬 지원2",
        content: "밑반찬 지원2",
        authorName: "관리자",
        thumbnailUrl: "/uploads/096629f9-8733-44ac-a7e9-50ea7cfa18f8.jpg",
        createdAt: parseShortDate("22.11.04"),
      },
      {
        board: BoardType.ALBUM,
        title: "밑반찬 지원1",
        content: "밑반찬 지원1",
        authorName: "관리자",
        thumbnailUrl: "/uploads/7cf25552-a53d-487d-a852-c44a05032267.png",
        createdAt: parseShortDate("22.08.25"),
      },
      {
        board: BoardType.ALBUM,
        title: "시각장애인가정 가족캠프2",
        content: "시각장애인가정 가족캠프2",
        authorName: "관리자",
        thumbnailUrl: "/uploads/d9eed2dd-d87c-4d64-b95a-7a853f10be52.jpg",
        createdAt: parseShortDate("22.08.16"),
      },
      {
        board: BoardType.ALBUM,
        title: "시각장애인가정 가족캠프1",
        content: "시각장애인가정 가족캠프1",
        authorName: "관리자",
        thumbnailUrl: "/uploads/0c1b618f-60f4-4aa1-b872-01a0ca4f0e81.jpg",
        createdAt: parseShortDate("22.08.16"),
      },
      {
        board: BoardType.ALBUM,
        title: "상록보육원 코딩교육",
        content: "상록보육원 코딩교육",
        authorName: "관리자",
        thumbnailUrl: "/uploads/f0225a36-8b35-4aa1-8ceb-7a379a082272.jpg",
        createdAt: parseShortDate("22.07.08"),
      },
      {
        board: BoardType.ALBUM,
        title: "시각장애부모의 비장애자녀 학습지원",
        content: "시각장애부모의 비장애자녀 학습지원",
        authorName: "관리자",
        thumbnailUrl: "/uploads/29f026bd-d6ad-4ec6-bfc2-1e0ec75409fa.jpg",
        createdAt: parseShortDate("22.06.24"),
      },
      {
        board: BoardType.ALBUM,
        title: "창립총회",
        content: "창립총회",
        authorName: "관리자",
        thumbnailUrl: "/uploads/bda68299-067e-43e1-9505-275e42b75d30.jpg",
        createdAt: parseShortDate("22.04.01"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/2e2ae5f3-a8d0-483c-8798-2e87d3f814b4.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/6c3e66a6-acf8-4cfa-a6a6-82548a121702.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/00e28158-66ab-476d-bed6-d8340241a914.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/81323e94-a844-4eea-b7d9-bbb02ce83135.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/8a20d93f-f3b2-41ed-8807-808f11d24df9.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/801cbace-4af1-4909-ade3-2a8fd255eb07.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/b57c537d-d034-40ab-8ca4-6237f3f7e8c6.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/0eb021bb-d9e8-4c46-afef-f9b7a2ce6343.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/f08f2016-8051-4fdd-8521-bdecafd9d96f.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
      {
        board: BoardType.ALBUM,
        title: "사단법인깊은순종 앨범게시판입니다...",
        content: "사단법인깊은순종 앨범게시판입니다...",
        authorName: "관리자",
        thumbnailUrl: "/uploads/59ea8ec6-5f62-46bb-96c1-2ccc70ef8023.jpg",
        createdAt: parseShortDate("22.03.29"),
      },
    ],
  });

  // 메인 화면 슬라이드 — 자체 보유 활동 사진 5장을 초기값으로 등록
  await prisma.heroSlide.deleteMany();
  const heroSlideFiles = albumImages.slice(0, 5);
  for (const [order, { uploadName }] of heroSlideFiles.entries()) {
    await prisma.heroSlide.create({
      data: { imageUrl: `/uploads/${uploadName}`, order },
    });
  }

  // 조직도 소개 배너 사진 — 초기값
  await prisma.siteImage.upsert({
    where: { key: "org-chart-banner" },
    update: { imageUrl: `/uploads/${albumImages[3].uploadName}` },
    create: {
      key: "org-chart-banner",
      imageUrl: `/uploads/${albumImages[3].uploadName}`,
    },
  });

  // 법인연혁 — 참고 사이트에서 옮겨온 연도별 실제 연혁
  await prisma.historyEntry.deleteMany();
  await prisma.historyEntry.createMany({
    data: [
      {
        year: "2020년",
        order: 0,
        content: [
          "설립추진단 결성 (1월)",
          "설립추진단 모임 및 목적사업에 대한 회의 (12월)",
        ].join("\n"),
      },
      {
        year: "2021년",
        order: 1,
        content: [
          "설립배경과 구체화된 목적사업에 대한 협의 (1월)",
          "설립동역자 모집 및 준비 모임 진행 (2~4월)",
          "창립총회 진행 (2021. 10. 31)",
        ].join("\n"),
      },
      {
        year: "2022년",
        order: 2,
        content: [
          "사단법인 깊은순종 설립허가 (2022. 3. 3)",
          "사단법인 깊은순종 법인등기 (2022. 3. 31)",
          "저소득 취약계층 무상급식 및 생활 지원(밑반찬) (2022. 4~)",
          "저소득 취약계층 자녀 교육 지원(시각장애인 부모의 자녀 교육) (2022. 4~)",
          "저소득 취약계층 의료비 지원 (2022. 4~)",
          "저소득 취약계층 의료비 지원(아동 심리 치료) (2022. 5~)",
          "지역의 사회복지시설을 통한 저소득 취약계층 자립 지원(컴퓨터 코딩교육) (2022. 7~) - 상록보육원",
          "사단법인 깊은순종 지정기부금단체 지정 (2022. 9. 30)",
          "지역의 사회복지시설을 통한 저소득 취약계층 자립 지원(컴퓨터 코딩교육) (2022. 12~) - 쪽방촌 소망을 찾는 이 지역아동센터",
        ].join("\n"),
      },
      {
        year: "2023년",
        order: 3,
        content: [
          "저소득 취약계층 의료비 지원(다문화가족 긴급 의료비 추가) (2023. 1~)",
          "저소득 취약계층 의료비 지원(아동 심리 치료) (2023. 1~)",
          "저소득 취약계층 자녀 교육 지원(시각장애인 부모의 자녀 교육) (2023. 1~)",
          "저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어발달 및 학습지도) (2023. 1~)",
          "쪽방촌 소망을 찾는 이 지역아동센터 컴퓨터 코딩교육 (2023. 1~)",
          "저소득 취약계층 무상급식 및 생활 지원(밑반찬, 다문화가족 긴급 생활비 추가) (2023. 1~)",
          "사단법인 깊은순종 2023-1차 이사회 (2023. 1. 29)",
          "사단법인 깊은순종 2023년 정기총회 (2023. 2. 26)",
          "저소득 취약계층 의료비 지원(아동 심리 치료 4명 추가) (2023. 6~)",
          "저소득 취약계층 무상급식 및 생활 지원(밑반찬 17명 추가) (2023. 6~)",
          "관악구 남현동 상록보육원 컴퓨터 코딩교육 (2023. 7, 8)",
        ].join("\n"),
      },
      {
        year: "2024년",
        order: 4,
        content: [
          "저소득 취약계층 의료비 지원 (2024. 1~)",
          "저소득 취약계층 아동 심리 치료 지원 (2024. 1~)",
          "저소득 취약계층 자녀 교육 지원(시각장애인 부모의 자녀 교육) (2024. 1~)",
          "저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어발달 및 학습지도) (2024. 1~)",
          "쪽방촌 소망을 찾는 이 지역아동센터 컴퓨터 코딩교육 (2024. 1~)",
          "저소득 취약계층 무상급식 및 생활 지원(밑반찬, 다문화가족 긴급 생활비) (2024. 1~)",
          "사단법인 깊은순종 2024-1차 이사회 (2024. 1. 28)",
          "사단법인 깊은순종 2024년 정기총회 (2024. 2. 25)",
          "저소득 취약계층 무상급식 및 생활 지원(밑반찬 2명 추가) (2024. 8~)",
          "관악구 신림동 한우리지역아동센터 컴퓨터 코딩교육 (2024. 7, 8)",
        ].join("\n"),
      },
      {
        year: "2025년",
        order: 5,
        content: [
          "사단법인 깊은순종 공익법인 재지정 (2025. 1)",
          "저소득 취약계층 의료비 지원 (2025. 1~)",
          "저소득 취약계층 아동 심리 치료 지원 (2025. 1~)",
          "저소득 취약계층 자녀 교육 지원(시각장애인 부모의 자녀 교육) (2025. 1~)",
          "저소득 취약계층 자녀 교육 지원(다문화가족 자녀 언어발달 및 학습지도) (2025. 1~)",
          "쪽방촌 소망을 찾는 이 지역아동센터 컴퓨터 코딩교육 (2025. 1~)",
          "저소득 취약계층 무상급식 및 생활 지원(밑반찬 보라매동 추가) (2025. 1~)",
          "관악구 신림동 하늘지역아동센터 컴퓨터 코딩교육 (2025. 1)",
          "사단법인 깊은순종 2025-1차 이사회 (2025. 1. 26)",
          "사단법인 깊은순종 2025년 정기총회 (2025. 2. 16)",
          "쪽방촌 소망을 찾는 이 지역아동센터 컴퓨터 코딩교육 1명 추가 지원 (2025. 5~)",
          "보건복지부장관 감사패 수상 (2025. 11. 20)",
        ].join("\n"),
      },
    ],
  });

  console.log("Seed complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
